### PR TITLE
remove unnecessary uses of guava, hide transitive dependency

### PR DESCRIPTION
**Pull request by RangerRick**
This PR gets rid of some minor uses of guava, and limits its use to the `config/` project, by shading the few dependencies we have.

### CODE REVIEW

**Comment by RangerRick** [comment]
ergh, running into maven bundle weirdness, making this a draft

**Comment by RangerRick** [comment]
aha! my `<configuration>` was missing an `<instructions>` level so my `<Import-Package>` guava exclude was being silently dropped

**Comment by RangerRick** [comment]
If I see one more use of `Sets.newHashSet()` I will scream. I'll give you [one guess why](https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Sets.java#L182)...

**Review by christianpape — APPROVED** [review]
LGTM.

**Pull request merged**
