### PR TITLE
OIA-20: Make OIA compile with Java11

### PR DESCRIPTION
**Pull request by cgorantla**

### CODE REVIEW

**Comment by cgorantla** [comment]
@indigo423  Since this build takes only about 1 min, should we also compile it with JDK8 ?

**Comment by indigo423** [comment]
@cgorantla We need at least Meridian 2019 to use something with the OIA plugin right? JDK 11 would be sufficient in my opinion.

**Comment by RangerRick** [comment]
Since you can still run 2019 under JDK8 I would think we should still _run_ our real CI builds against 8, but commit only the fixes that make it so you _can_ build with 11 IMHO.  (Ideally, we'd make a separate `build-jdk11` job but rely on the `build` one for the `deploy` step.)

**Comment by cgorantla** [comment]
@indigo423 @RangerRick  Reviving this. 
Since OpenNMS compiles on Java11 by default, I think it would be good to move this also Java11.

**Review by indigo423 — APPROVED** [review]
LGTM! Java 11 :tada:

**Comment by RangerRick** [comment]
I would say the `pom.xml` should get bumped to `0.7.0` rather than being a micro-update if the dependencies are changing.

**Review by RangerRick — APPROVED** [review]
other than the pom version, looks fine to me

**Comment by cgorantla** [comment]
> I would say the `pom.xml` should get bumped to `0.7.0` rather than being a micro-update if the dependencies are changing.

Moved version to 0.7.0-SNAPSHOT

**Pull request merged**
