### PR TITLE
OIA-28: Add gRPC API for Integration API

### PR DESCRIPTION
**Pull request by cgorantla**

### CODE REVIEW

**Comment by j-white** [comment]
Can we keep the gRPC support as a plugin rather than pulling it into the OIA?

**Comment by cgorantla** [comment]
> Can we keep the gRPC support as a plugin rather than pulling it into the OIA?
> 
> My concern here is that it is incomplete and this will add a whole other set of mappings to maintain.

My thinking was that `proto` files should be here so that's all users need to know.  OIA gRPC Server kar  link can be provided in the readme.

**Comment by j-white** [comment]
> My thinking was that `proto` files should be here so that's all users need to know. OIA gRPC Server kar link can be provided in the readme.

Then the .proto files become versioned with the OIA, whereas they should be really be versioned with implementation in the gRPC server.

**Comment by cgorantla** [comment]
> > My thinking was that `proto` files should be here so that's all users need to know. OIA gRPC Server kar link can be provided in the readme.
> 
> Then the .proto files become versioned with the OIA, whereas they should be really be versioned with implementation in the gRPC server.

Okay. Closing it then.

**Pull request closed without merging**
